package br.inatel.GymPower.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class InicioMDI extends javax.swing.JFrame {

    public InicioMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon ("src\\imagens\\fundo.jpg");
                Image i = im.getImage();

                g.drawImage(i, 0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuCadastrarAluno = new javax.swing.JMenuItem();
        mnuCadastraParceiro = new javax.swing.JMenuItem();
        mnuCadastrarAlunoAula = new javax.swing.JMenuItem();
        mnuConsultarAluno = new javax.swing.JMenuItem();
        mnuConsultaAlunoAula = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuConsultarProfessor = new javax.swing.JMenuItem();
        mnuCadastrarProfessorAula = new javax.swing.JMenuItem();
        mnuConsultarTodosFuncionario = new javax.swing.JMenuItem();
        mnuConsultarAulas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym Power");
        setResizable(false);

        pnlBack.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlBackLayout = new javax.swing.GroupLayout(pnlBack);
        pnlBack.setLayout(pnlBackLayout);
        pnlBackLayout.setHorizontalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        pnlBackLayout.setVerticalGroup(
            pnlBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnuInicio.setText("Inicio");
        mnuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuInicio);

        jMenu2.setText("Aluno");

        mnuCadastrarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/005-student.png"))); // NOI18N
        mnuCadastrarAluno.setText("Cadastrar Aluno");
        mnuCadastrarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuCadastrarAlunoMousePressed(evt);
            }
        });
        mnuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadastrarAluno);

        mnuCadastraParceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/008-parceiro.jpg"))); // NOI18N
        mnuCadastraParceiro.setText("Parceiros");
        mnuCadastraParceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuCadastraParceiroMousePressed(evt);
            }
        });
        mnuCadastraParceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastraParceiroActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadastraParceiro);

        mnuCadastrarAlunoAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/006-students.png"))); // NOI18N
        mnuCadastrarAlunoAula.setText("Cadastrar Aluno na Aula");
        mnuCadastrarAlunoAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuCadastrarAlunoAulaMousePressed(evt);
            }
        });
        jMenu2.add(mnuCadastrarAlunoAula);

        mnuConsultarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/007-aluna.png"))); // NOI18N
        mnuConsultarAluno.setText("Consultar Aluno");
        mnuConsultarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuConsultarAlunoMousePressed(evt);
            }
        });
        jMenu2.add(mnuConsultarAluno);

        mnuConsultaAlunoAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/001-online-class.png"))); // NOI18N
        mnuConsultaAlunoAula.setText("Consultar Aulas do Aluno");
        mnuConsultaAlunoAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuConsultaAlunoAulaMousePressed(evt);
            }
        });
        jMenu2.add(mnuConsultaAlunoAula);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Funcionário");

        mnuConsultarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/003-instructor-1.png"))); // NOI18N
        mnuConsultarProfessor.setText("Consultar Professor");
        mnuConsultarProfessor.setEnabled(false);
        mnuConsultarProfessor.setOpaque(true);
        jMenu3.add(mnuConsultarProfessor);

        mnuCadastrarProfessorAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/002-instructor.png"))); // NOI18N
        mnuCadastrarProfessorAula.setText("Cadastrar Professor na Aula");
        mnuCadastrarProfessorAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuCadastrarProfessorAulaMousePressed(evt);
            }
        });
        jMenu3.add(mnuCadastrarProfessorAula);

        mnuConsultarTodosFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/004-staff.png"))); // NOI18N
        mnuConsultarTodosFuncionario.setText("Consultar Todos Funcionários");
        mnuConsultarTodosFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuConsultarTodosFuncionarioMousePressed(evt);
            }
        });
        jMenu3.add(mnuConsultarTodosFuncionario);

        jMenuBar1.add(jMenu3);

        mnuConsultarAulas.setText("Visualizar Todas as Aulas");
        mnuConsultarAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuConsultarAulasMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuConsultarAulas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuConsultarAulasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultarAulasMousePressed

        TlConsultaAula consultaAula = new TlConsultaAula();
        setContentPane(consultaAula);
        revalidate();

    }//GEN-LAST:event_mnuConsultarAulasMousePressed

    private void mnuInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInicioMousePressed

        setContentPane(pnlBack);
        revalidate();

    }//GEN-LAST:event_mnuInicioMousePressed

    private void mnuConsultaAlunoAulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultaAlunoAulaMousePressed

        TlConsultaAlunoAula consultaAulaAluno = new TlConsultaAlunoAula();
        setContentPane(consultaAulaAluno);
        revalidate();

    }//GEN-LAST:event_mnuConsultaAlunoAulaMousePressed

    private void mnuConsultarTodosFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultarTodosFuncionarioMousePressed

        TlConsultarTodosFuncionario consultaTodosFuncionario = new TlConsultarTodosFuncionario();
        setContentPane(consultaTodosFuncionario);
        revalidate();

    }//GEN-LAST:event_mnuConsultarTodosFuncionarioMousePressed

    private void mnuConsultarAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuConsultarAlunoMousePressed

        TlConsultarAluno consultarAluno = new TlConsultarAluno();
        setContentPane(consultarAluno);
        revalidate();

    }//GEN-LAST:event_mnuConsultarAlunoMousePressed

    private void mnuCadastrarAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCadastrarAlunoMousePressed

        TlCadastrarAluno cadastrarAluno = new TlCadastrarAluno();
        setContentPane(cadastrarAluno);
        revalidate();

    }//GEN-LAST:event_mnuCadastrarAlunoMousePressed

    private void mnuCadastrarAlunoAulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCadastrarAlunoAulaMousePressed

        TlCadastrarAlunoAula cadastrarAlunoAula = new TlCadastrarAlunoAula();
        setContentPane(cadastrarAlunoAula);
        revalidate();

    }//GEN-LAST:event_mnuCadastrarAlunoAulaMousePressed

    private void mnuCadastrarProfessorAulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCadastrarProfessorAulaMousePressed

        TlCadastrarProfessorAula cadastrarProfessor = new TlCadastrarProfessorAula();
        setContentPane(cadastrarProfessor);
        revalidate();

    }//GEN-LAST:event_mnuCadastrarProfessorAulaMousePressed

    private void mnuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrarAlunoActionPerformed

    private void mnuCadastraParceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastraParceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastraParceiroActionPerformed

    private void mnuCadastraParceiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCadastraParceiroMousePressed
        TlCadastrarParceiro cadastrarParceiro = new TlCadastrarParceiro();
        setContentPane(cadastrarParceiro);
        revalidate();
    }//GEN-LAST:event_mnuCadastraParceiroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastraParceiro;
    private javax.swing.JMenuItem mnuCadastrarAluno;
    private javax.swing.JMenuItem mnuCadastrarAlunoAula;
    private javax.swing.JMenuItem mnuCadastrarProfessorAula;
    private javax.swing.JMenuItem mnuConsultaAlunoAula;
    private javax.swing.JMenuItem mnuConsultarAluno;
    private javax.swing.JMenu mnuConsultarAulas;
    private javax.swing.JMenuItem mnuConsultarProfessor;
    private javax.swing.JMenuItem mnuConsultarTodosFuncionario;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
