package br.inatel.GymPower.view;

import br.inatel.GymPower.controller.FuncionarioController;
import br.inatel.GymPower.model.Funcionario;
import br.inatel.GymPower.model.Instrutor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class TlConsultarTodosFuncionario extends javax.swing.JPanel {

    DefaultTableModel vTabela = new DefaultTableModel();
    FuncionarioController fController = new FuncionarioController();

    public TlConsultarTodosFuncionario() {
        initComponents();
        vTabela.addColumn("Matricula");
        vTabela.addColumn("Nome");
        vTabela.addColumn("Cargo");
        vTabela.addColumn("Telefone");
        vTabela.addColumn("Data de Nascimento");
        vTabela.addColumn("E-mail");
        vTabela.addColumn("Qntd de Aulas");
        vTabela.addColumn("Salário");
        PreencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaTodosFuncionario = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Consulta de todos os funcionários");

        tblTabelaTodosFuncionario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblTabelaTodosFuncionario.setModel(vTabela);
        jScrollPane1.setViewportView(tblTabelaTodosFuncionario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void PreencherTabela() {
        //Limpar a tabela
        int t = vTabela.getRowCount();
        for (int i = 0; i < t; i++) {
            vTabela.removeRow(0);
        }

        ArrayList<Funcionario> lista = fController.buscaFuncionarios();

        for (int i = 0; i < lista.size(); i++) {
            String linha[] = new String[8];

            linha[0] = lista.get(i).getMatricula() + "";
            linha[1] = lista.get(i).getNome();
            linha[2] = lista.get(i).getCargo();
            linha[3] = lista.get(i).getTelefone();
            linha[4] = lista.get(i).getDataNascimento();
            linha[5] = lista.get(i).getEmail();

            if (lista.get(i) instanceof Instrutor) {
                Instrutor iaux = (Instrutor) lista.get(i);
                linha[6] = iaux.getQtdAulas() + "";
                linha[7] = iaux.getSalarioAjustado() + "";
            } else {
                linha[6] = " - ";
                linha[7] = " - ";
            }

            vTabela.addRow(linha);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabelaTodosFuncionario;
    // End of variables declaration//GEN-END:variables
}
